name: .NET

on:
  push:
    branches: [ bahioganns ]
  pull_request:
    branches: [ bahioganns ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 3.1
    - name: List files
      run: ls -la
    - name: Restore dependencies
      run: dotnet restore Lab1.sln
    - name: Build
      run: dotnet build --no-restore Lab1.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal Lab1.sln
