name: Labs Build And Tests

on:
  push:
    branches: [ cuamckuu_lab1 ]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.0'
    - name: Restore dependencies
      run: dotnet restore labs.sln
    - name: Build
      run: dotnet build --no-restore labs.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal labs.sln
